
name: ci
on: push
jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Markdown test
        uses: actionshub/markdownlint@v1.0.0
